Feat/notification push
Godefroy/rolebase pull request #89
Opened 2023-04-14 09:57 UTC by Code-Hello

- add push notification using Novu FCM integration
- update pwa

2023-04-15 17:20 UTC, Godefroy requested changes
Ca a pas du être évident cette PR, GG 👏

La qualité des images que tu as rajoutées ne semble pas bonne. Je recommande pour cela de recréer des png à partir du svg. Pour cela une méthode simple est de modifier la taille (width & height) de icon.svg puis de le passer dans https://svgtopng.com/

J'ai l'impression que tu as laissé des images qui étaient utilisées dans l'ancien manifest et qui ne sont plus utilisées nulle part. Tu peux vérifier ?

D'ailleurs es-tu sûre qu'avec les images déjà présentes dans l'ancien manifest ça ne suffisait pas ?

2023-04-15 17:20 UTC, Godefroy commented on public/firebase-messaging-sw.js
> +/* eslint-disable no-undef */
Ce fichier semble redondant avec `src/api/firebase.ts`
Et les imports de compat sont-ils vraiment utiles ?

2023-04-15 17:20 UTC, Godefroy commented on src/components/routes/PrivateRoute.tsx
> +      .catch((err) => console.error(err))
Est-ce qu'on doit vraiment faire ça à chaque chargement de page ?
À quoi ça sert si c'est juste pour afficheer un console.log ?

2023-04-15 17:20 UTC, Godefroy commented on .gitignore
> +dev-dist
C'est utilisé par quoi ?

2023-04-17 08:08 UTC, Code-Hello commented on .gitignore
> +dev-dist
Par la lib que j'ai mise pour la pwa, ça permet de pouvoir faire les tests en dev et ne pas avoir à build et lancer la prod à chaque fois. Mais donc à ne pas push d'où l'ajout dans le gitignore
[Vite-pwa](https://vite-pwa-org.netlify.app/guide/)

2023-04-17 08:28 UTC, Code-Hello commented on src/components/routes/PrivateRoute.tsx
> +      .catch((err) => console.error(err))
Dans les différents exemples, c'est mis dans le `App.ts` mais le soucis chez nous c'est qu'on ne veut l'utiliser si on est pas co et sur une route préviée donc d'où l'utilisation ici mais à voir s'il y a mieux comme ça je ne vois pas je dois avouer

Il ne fait pas qu'afficher un console log mais écoute en fond les push et resolve les notif (cf `firebase.ts`) dans le cas où l'appli est en premier plan

2026-09-07 18:26 UTC, closed without merging